### ISSUE TITLE
I'd like to contribute

### ISSUE THREAD

**Issue by alchemy-color** [abpy/color-neg-resources#2]

**Comment by abpy** [comment]
Hi, I'm glad to see you have found this process helpful. I would be interested to hear your thoughts/ideas if you're still interested in sharing.

**Comment by alchemy-color** [comment]
Deleted the comment by accident.

It was something along the lines of "I found this process really inspiring and extremely useful and I would like to contribute with some ideas". 

![image](https://github.com/user-attachments/assets/4ba19dd8-2681-48c6-b9cc-740b826f6f84)![image](https://github.com/user-attachments/assets/bcf5717d-7933-469a-a687-bddaa58c92a5)

I'm making a video that integrates your process along with some other techniques with my own products.

In the spirit of open source software, I guess I should just publish everything here right?

**Comment by abpy** [comment]
I did look up your user-name to find your youtube channel, I liked your video on calibration. I think a video about negative scanning could turn out very well.

Your film scans do look pretty good. If you have any questions or need clarification about the process feel free to ask.

There is no reason your work has to be open source unless you want it to be, you can publish it however you see is best.

**Comment by alchemy-color** [comment]
Hi again,
Here's what I was cooking for the past week or so.
https://github.com/alchemy-color/color-negative-inversion/

**Comment by abpy** [comment]
This looks great, I'm glad you were able to adapt this process to your workflow.
I'm curious how raw white balance has an effect on your colors. I have found that the inversion is best when the base color is still a bit orange-ish before density balance. Maybe if the backlight is narrow-band rgb it makes less of a difference.

**Comment by alchemy-color** [comment]
Here’s what I discovered:

- Creating a linear DCP profile removes the tone curve designed to work with other profile components, such as matrix and LUT. The result is a linear Adobe Standard profile that appears very desaturated and often leads to bland conversions.
  
- The ACR-to-linear curve in my repository modifies the image after applying the DNG profile. I tested it against a linearized Adobe Standard profile made with dcptool, DNG Profile Editor, or Lumariver. Applying the curve downstream results in a more natural color rendition. While experimenting with the "Refine Saturation" slider on the curves tab, I found that lowering the slider increases saturation in the upper half of the tonal range. It can be tempting to use, but it often leads to uneven saturation distribution.

- The real advantage of using this curve is its compatibility with a wide range of cameras. Despite the variations across Adobe Standard profiles, the resulting TIFF file is generally satisfactory.

- I’ve experimented with white-balancing using a known neutral point, as well as keeping the image set at the illuminant white point. With the Adobe Standard + ACR-to-linear curve, white-balancing to a known neutral dark (which appears bright in the negative) provided more consistent grays across the tonal range. Adobe Standard is dual a illuminant profile that works well for this purpose. DNG scans from Vuescan come with an empty embedded DNG profile. With these scans I leave white balance alone. 

- I captured my negatives using a Sony A7IV and an iPad as the backlight. The spectral distribution, which is peaky, is similar to the light source used in a Fuji SP3000. This improves color separation, but certain colors like yellows and greens appeared overly saturated and bright. This led me to experiment with RA4 print paper ICC profiles. I downloaded several of them and converted them to .cube using Lattice. The tonal curve was flattened, so only color transformation occurred.

- In the template, the Kodak Endura color profile paired with your Endura contrast gave me the most natural-looking colors. Interestingly, when using a high-quality, spectrally consistent LED light source (YujiLED D50) to illuminate the negatives, there was no need for paper color emulation to achieve an accurate inversion. However, this opens up a complex topic I’m not ready to dive into just yet...

- I also modified some of the paper contrast LUTs to ensure peak white and black levels could be achieved, along with a combination of fogged blacks and whites.

- While REC.2020 is solid, ACEScg is even better, especially when dealing with saturated dark colors like purples.

- The most accurate conversion—both in terms of matching the SG reference values and overall visual appeal—was achieved using the iPad backlight, with Sony A7IV files processed through the D50-calibrated profile available on my website. For white balance, I relied on readings from an i1Pro3, rather than white-balancing to the white background in Lightroom. My profiles are single-illuminant, so I had to leave the camera white balance set to the iPad’s white point, which is around 6300K.

**Comment by abpy** [comment]
Though not all of your findings match mine, It makes sense that different things would work for different setups. I have found that too bright yellow/green can be related to the white balance or the camera profile.

**Comment by alchemy-color** [comment]
It’s tricky to decide what profile to make for such a usage scenario. I’ve experimented with simple, matrix only profiles for D50 and StdA, both with WB set to a known neutral or to the white point of the backlight. The Sony A7IV get super close to a calibrated response with a matrix only. It’s an easy camera to calibrate. 

I even experimented with a complex profile (Matrix+2 LUTs) for the light source of the iPad itself: I illuminated a ColorChecker SG with an iPad and created a camera profile. Out of all of these, the D50, coupled with a paper emulation looked the best.

I guess the peaky nature of the backlight, coupled with the color of film makes DSLR scanning a moving target.
What do you think?

**Comment by alchemy-color** [comment]
Actually, I revisited the workflow where the camera profile is created based on a color chart illuminated by the iPad. The resulting neg>pos conversion doesn't require a paper gamut layer at all. Here's an example.

![01_DSC06926_+01EV copy](https://github.com/user-attachments/assets/2dfb59f0-82ce-4828-bc0f-0477cf8ab30e)

**Comment by abpy** [comment]
I do have a few more thoughts on film and profiling:

- my dcamprof profile is very similar to the adobe standard linear one.

- scans with a peaky light spectrum likely require a different calibration than white light. (it seems this is the case with your new profile)

- It is possible to get very nice colors with a broad spectrum backlight and a standard camera profile.
The dye absorption of a white light scan adds a look to the film that is similar to a print.

- I have not tried a narrow-band (peaky) light source, but I would expect it produces brighter colors and requires less density corrections.

- A "perfect" film scan would be almost indistinguishable from a digital photo. While this would show the true capabilities of film, it's probably not what most film photographers would expect.


I only know what works and doesn't work for my own film and camera. I am not able to test many different setups so I can't say what works best for all of them. I am not set up to scan film right now so I cant do any new tests, but I did try processing a scan from a different camera. I found that requires different raw settings, and profiles with gamut compression can cause desaturated colors if the white balance is too warm.

You may find some of these discussions interesting:
[https://discuss.pixls.us/t/any-interest-in-a-film-negative-feature-in-rt/12569/362](https://discuss.pixls.us/t/any-interest-in-a-film-negative-feature-in-rt/12569/362)
